// ? SVG code definitions
const weatherIcons = new Map<number, string>()

const weatherIconsDef: { [key: number]: string } = {
  200: '/assets/cloud_lightning_heavyrain.svg',
  201: '/assets/cloud_lightning_heavyrain.svg',
  202: '/assets/cloud_lightning_heavyrain.svg',
  210: '/assets/cloud_lightning_heavyrain.svg',
  211: '/assets/cloud_lightning_heavyrain.svg',
  212: '/assets/cloud_lightning_heavyrain.svg',
  221: '/assets/cloud_lightning_heavyrain.svg',
  230: '/assets/cloud_lightning_heavyrain.svg',
  231: '/assets/cloud_lightning_heavyrain.svg',
  232: '/assets/cloud_lightning_heavyrain.svg',
  300: '/assets/3_waterdrop.svg',
  301: '/assets/3_waterdrop.svg',
  302: '/assets/3_waterdrop.svg',
  310: '/assets/3_waterdrop.svg',
  311: '/assets/3_waterdrop.svg',
  312: '/assets/3_waterdrop.svg',
  313: '/assets/3_waterdrop.svg',
  314: '/assets/3_waterdrop.svg',
  321: '/assets/3_waterdrop.svg',
  500: '/assets/cloud_sing_waterdrop.svg',
  501: '/assets/cloud_sing_waterdrop.svg',
  502: '/assets/cloud_heavyrain.svg',
  503: '/assets/cloud_heavyrain.svg',
  504: '/assets/cloud_heavyrain.svg',
  511: '/assets/cloud_heavyrain.svg',
  520: '/assets/cloud_sing_waterdrop.svg',
  521: '/assets/cloud_sing_waterdrop.svg',
  522: '/assets/cloud_heavyrain.svg',
  531: '/assets/cloud_heavyrain.svg',
  600: '/assets/cloud_sing_snowflake.svg',
  601: '/assets/cloud_sing_snowflake.svg',
  602: '/assets/cloud_3_snowflake.svg',
  611: '/assets/cloud_3_snowflake.svg',
  612: '/assets/cloud_sing_snowflake.svg',
  613: '/assets/cloud_3_snowflake.svg',
  615: '/assets/cloud_sing_snowflake.svg',
  616: '/assets/cloud_sing_snowflake.svg',
  620: '/assets/cloud_sing_snowflake.svg',
  621: '/assets/cloud_3_snowflake.svg',
  622: '/assets/cloud_3_snowflake.svg',
  701: '/assets/waves.svg',
  711: '/assets/waves.svg',
  721: '/assets/waves.svg',
  731: '/assets/waves.svg',
  741: '/assets/waves.svg',
  751: '/assets/waves.svg',
  761: '/assets/waves.svg',
  762: '/assets/waves.svg',
  771: '/assets/waves.svg',
  781: '/assets/tornado.svg',
  800: '/assets/full_sun.svg',
  801: '/assets/cloud_sun.svg',
  802: '/assets/cloud_sun.svg',
  803: '/assets/cloud_sun.svg',
  804: '/assets/cloud.svg',
}

Object.entries(weatherIconsDef).forEach(([key, value]) => {
  weatherIcons.set(parseInt(key), value)
})

export default weatherIcons
