# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: 
      - dev 
      - main 
    paths-ignore: 
      - 'README.md'
  pull_request:
    branches: 
      - dev 
      - main 
    paths-ignore: 
      - 'README.md'


  
jobs:
  build:

    runs-on: windows-latest

        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js '18'
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Clear Cache 
      run: pnpm store prune 
    - name: Install dependencies 
      run: pnpm ci
    - name: building Application
      run: pnpm run build --if-present
    - name: testing Application 
      run: pnpm test --passWithNoTests
